FROM php:apache-stretch

ARG hostname

RUN mkdir /var/www/html/${hostname}

COPY host.conf /etc/apache2/sites-available/${hostname}.conf
COPY index.html /var/www/html/${hostname}/index.html

RUN sed -i 's/HOST/$hostname/g' /etc/apache2/sites-available/$hostname.conf
RUN sed -i 's/HELLO/$hostname/g' /var/www/html/$hostname/index.html

RUN a2ensite ${hostname}.conf