version: "3.7"
services:
  nginx-proxy:
      image: jwilder/nginx-proxy
          container_name: nginx-proxy
              expose:
                    - "80"
                          - "443"
                              volumes:
                                    - certs:/etc/nginx/certs
                                          - vhost:/etc/nginx/vhost.d
                                                - html:/usr/share/nginx/html
                                                      - /var/run/docker.sock:/tmp/docker.sock:ro
                                                          privileged: true
                                                            nginx-proxy-letsencrypt:
                                                                image: jrcs/letsencrypt-nginx-proxy-companion
                                                                    volumes:
                                                                          - /var/run/docker.sock:/var/run/docker.sock
                                                                                - certs:/etc/nginx/certs
                                                                                      - vhost:/etc/nginx/vhost.d
                                                                                            - html:/usr/share/nginx/html
                                                                                                environment:
                                                                                                      - "DEFAULT_EMAIL=bader.richard@kozut.hu"
                                                                                                            - "NGINX_PROXY_CONTAINER=nginx-proxy"
                                                                                                                privileged: true
                                                                                                                  registry:
                                                                                                                      image: registry
                                                                                                                          ports:
                                                                                                                                - "443:5000"
                                                                                                                                    restart: always
                                                                                                                                        volumes:
                                                                                                                                              - registry:/var/lib/registry:Z
                                                                                                                                                  environment:
                                                                                                                                                        - "VIRTUAL_HOST=docker2.vagyok.com"
                                                                                                                                                              - "LETSENCRYPT_HOST=docker2.vagyok.com"
                                                                                                                                                              volumes:
                                                                                                                                                                registry:
                                                                                                                                                                  certs:
                                                                                                                                                                    vhost:
                                                                                                                                                                    